version: '3'
services:
  app:
    build:
      context: ./.docker
      dockerfile: Dockerfile
    image: php-fpm-alpine/7.3
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - default

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default

  mysql:
    image: mysql:5
    command: --explicit_defaults_for_timestamp=1 --innodb_use_native_aio=0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./.docker/data/:/var/lib/mysql/
    networks:
      - default

networks:
  default:
    driver: bridge
